In [1]:
import numpy as np

In [2]:
array_a = np.array([[1,2,3,],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
array_a = np.array([1,2,3,],[4,5,6], dtype = np.int64)

TypeError: argument for array() given by name ('dtype') and position (position 1)

In [4]:
import numpy.testing as testing

In [5]:
array_a.dtype

dtype('int64')

In [6]:
np.data_type = "data_type"

In [7]:
array_a = np.array([1,2,3],[4,5,6], dtype = np.bool)
array_a()

/var/folders/qg/ssrxdx1x2wd8frrb53jy7yzc0000gn/T/ipykernel_72366/2792907955.py:1: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  array_a = np.array([1,2,3],[4,5,6], dtype = np.bool)


AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [8]:
array_a.dtype

dtype('int64')

In [9]:
array_a (dtype = np.complex)

AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [10]:
array_a.dtype

dtype('int64')

In [11]:
  array_a.dtype

dtype('int64')

In [12]:
array_a = np.array([])


In [13]:
array_a = np.array([1,2,3],[4,5,6], dtype = np.bool)
array_a()

/var/folders/qg/ssrxdx1x2wd8frrb53jy7yzc0000gn/T/ipykernel_72366/2792907955.py:1: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  array_a = np.array([1,2,3],[4,5,6], dtype = np.bool)


AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

# Numpy function

In [14]:
array_x = np.array([1,2,3])
array_x

array([1, 2, 3])

In [15]:
array_y = np.array([[1,4,5],[2,1,4]])
array_y

array([[1, 4, 5],
       [2, 1, 4]])

In [16]:
np.add(array_x ,array_y)

array([[2, 6, 8],
       [3, 3, 7]])

In [17]:
np.subtract(array_x,array_y)

array([[ 0, -2, -2],
       [-1,  1, -1]])

In [18]:
np.multiply(array_x,array_y)

array([[ 1,  8, 15],
       [ 2,  2, 12]])

In [19]:
array_x+array_y

array([[2, 6, 8],
       [3, 3, 7]])

In [20]:
np.add(array_x,array_y ,dtype= np.float64)

array([[2., 6., 8.],
       [3., 3., 7.]])

In [21]:
np.add(aaray_x,array_y , dtype = np.str)

NameError: name 'aaray_x' is not defined

In [22]:
np.mean(array_x, axis=0)

2.0

In [23]:
def __init__(self,name):
       self :
        

SyntaxError: invalid syntax (2031074655.py, line 2)

In [24]:
matrix_a = np.array([[1,2,3],[4,5,6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
matrix_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

# BASIC SLICING

In [29]:
matrix_a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
matrix_a[0:0]

array([], shape=(0, 3), dtype=int64)

In [31]:
matrix_a[1:3]

array([[4, 5, 6]])

In [32]:
matrix_a [0:0]

array([], shape=(0, 3), dtype=int64)

In [33]:
type(matrix_a)

numpy.ndarray

In [34]:
matrix_a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
matrix_a[:1]

array([[1, 2, 3]])

In [36]:
matrix_a [:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
matrix_a[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
matrix_a[1]

array([4, 5, 6])

In [39]:
matrix_a[:-1]

array([[1, 2, 3]])

In [40]:
matrix_a[-1]

array([4, 5, 6])

In [41]:
matrix_a[0:6]

array([[1, 2, 3],
       [4, 5, 6]])

Stepwise slicing

In [42]:
matrix_b = np.array([[1,2,3,5,6],[3,6,7,8,9],[5,6,7,8,6]])
matrix_b

array([[1, 2, 3, 5, 6],
       [3, 6, 7, 8, 9],
       [5, 6, 7, 8, 6]])

In [43]:
matrix_b [:,:]

array([[1, 2, 3, 5, 6],
       [3, 6, 7, 8, 9],
       [5, 6, 7, 8, 6]])

In [44]:
matrix_b [::2,::2]>3

array([[False, False,  True],
       [ True,  True,  True]])

In [45]:
matrix_b[:]>0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [46]:
matrix_b[matrix_b[:,:]>4]

array([5, 6, 6, 7, 8, 9, 5, 6, 7, 8, 6])

In [47]:
type(matrix_b)

numpy.ndarray

In [48]:
print(matrix_b)

[[1 2 3 5 6]
 [3 6 7 8 9]
 [5 6 7 8 6]]


matrix_b[1,2,3]

In [49]:
print(matrix_b[0:0].shape)
print(matrix_b[0,0:1].shape)

(0, 5)
(1,)


In [50]:
matrix_b[0:0:1].squeeze

<function ndarray.squeeze>

In [51]:
print(matrix_b[0,0:1].shape)

(1,)


In [52]:
print(matrix_b[0,0:1].shape)

(1,)


In [53]:
np.squeeze(matrix_b)

array([[1, 2, 3, 5, 6],
       [3, 6, 7, 8, 9],
       [5, 6, 7, 8, 6]])

In [54]:
np.squeeze(matrix_b)

array([[1, 2, 3, 5, 6],
       [3, 6, 7, 8, 9],
       [5, 6, 7, 8, 6]])

In [55]:
r  = np.array([[1,2],[3,4],[5,6]])
e = [[1,2],[3,4],[5,6]]

In [56]:
r [0,:] + r[1,:]

array([4, 6])

In [57]:
e[0]+e[1]

[1, 2, 3, 4]

In [58]:
r[2,:] + e[1]

array([ 8, 10])

In [59]:
s = np.array([[1,2,3],[4,5,6]])

In [60]:
s[0]

array([1, 2, 3])

In [61]:
s[0] + s[0,:]

array([2, 4, 6])

In [62]:
s[-1]

array([4, 5, 6])

In [63]:
a = np.array([[12,-3,4,7],[23,31,-12,10],[24,9,18,15],[81,5,6,1],[-10,18,17,29]])

In [64]:
a[::2,1::3]

array([[-3],
       [ 9],
       [18]])

# BASIC SLICING AGAIN

In [65]:
matrix_b = np.array([[1,2,3,4,5],[4,5,6,8,9]])
matrix_b 

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 9]])

In [66]:
matrix_b[:]

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 9]])

In [67]:
matrix_b[2::,2::]


array([], shape=(0, 3), dtype=int64)

In [68]:
matrix_b[1::,3::]

array([[8, 9]])

In [69]:
matrix_b[0::,3::]

array([[4, 5],
       [8, 9]])

In [70]:
matrix_b[2::,3::]

array([], shape=(0, 2), dtype=int64)

In [71]:
type[matrix_b]

type[array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 9]])]

In [72]:
print(([matrix_b]).dtype == 'bool')

AttributeError: 'list' object has no attribute 'dtype'

In [73]:
matrix_b[::2
        ,::4]

array([[1, 5]])

In [74]:
matrix_b[::4]

array([[1, 2, 3, 4, 5]])

In [90]:
matrix_b[:,::9]

array([[1],
       [4]])

In [77]:
matrix_b[::3]

array([[1, 2, 3, 4, 5]])

In [82]:
matrix_b[2:,:1]
         
         
         
         


array([], shape=(0, 1), dtype=int64)

Stepwise slicing

In [84]:
matrix_b[2:]

array([], shape=(0, 5), dtype=int64)

In [88]:
matrix_b[2:3:2,::-1]

array([], shape=(0, 5), dtype=int64)

In [100]:
matrix_b[0:3:2,2:5:1]

array([[3, 4, 5]])

In [101]:
matrix_b[:,:]>2

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [102]:
matrix_b[0:2]

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 9]])

In [104]:
matrix_b[0:22]

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 9]])

In [109]:
matrix_b[:2:,3:]

array([[4, 5],
       [8, 9]])